import { Outfit, JetBrains_Mono } from "next/font/google";
import type { Metadata } from "next";
import "@/styles/global.css";
import "@/styles/theme.css";
import Header from "@/components/Header/Header";
import Sidebar from "@/components/Sidebar/Sidebar";

const outfitSans = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const jetBrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${outfitSans.variable} ${jetBrainsMono.variable}`}>
        <Header />
        <Sidebar />
        <main>
          <p>{children}</p>
        </main>
      </body>
    </html>
  );
}
